### Autograd

In [21]:
import numpy as np
import torch
device = "cuda:0" if torch.cuda.is_available() else "cpu"
device

'cuda:0'

**Calculate the gradient so we can backpropagate**

In [51]:
x = torch.randn(3, requires_grad=True)
x

tensor([ 0.9124, -0.4436,  0.4509], requires_grad=True)

In [52]:
# node: x + 2 -> y
y = x + 2
y

tensor([2.9124, 1.5564, 2.4509], grad_fn=<AddBackward0>)

In [55]:
# node: y * y * 2 -> z
z = y * y * 2
z = z.mean()
z

tensor(11.2742, grad_fn=<MeanBackward0>)

In [56]:
z.backward() # dz/dx
x.grad

tensor([5.0482, 8.3006, 3.2777])

**Setting grad to false to avoid computational graph during training**

In [58]:
x.requires_grad_(False) # no grad
x

tensor([ 0.9124, -0.4436,  0.4509])

In [59]:
y = x.detach() # no grad

In [60]:
with torch.no_grad(): # no grad
    y = x + 2
    print(y)

tensor([2.9124, 1.5564, 2.4509])


**Dummie training example**

In [64]:
weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
    model_output = (weights * 3).sum()
    model_output.backward()

    print(weights.grad)

    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
