In [1]:
import torch

In [48]:
device = "cuda:0" if torch.cuda.is_available() else "cpu"
device

'cuda:0'

**Empty tensors**

In [3]:
x = torch.empty(2, 2, 3)
x

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])

**Random tensors**

In [4]:
x = torch.rand(2, 2)
x

tensor([[0.1373, 0.3772],
        [0.4009, 0.0188]])

**One's tensors**

In [13]:
x = torch.ones(3, 2, dtype=torch.int32)
x.dtype, x

(torch.int32,
 tensor([[1, 1],
         [1, 1],
         [1, 1]], dtype=torch.int32))

In [14]:
x.size()

torch.Size([3, 2])

**Custom tensors**

In [15]:
x = torch.tensor([2.5, 0.1])
x

tensor([2.5000, 0.1000])

**Tensors operations**

In [28]:
# Sum
x = torch.rand(3, 2)
y = torch.rand(3, 2)

z = x + y
z = torch.add(x, y)
z = y.add_(x)
print(f"{x + y} \n equals to \n {torch.add(x, y)} \n equals to \n {y.add_(x)}") 

tensor([[2.3027, 2.1648],
        [2.5719, 2.4407],
        [2.3651, 0.2811]]) 
 equals to 
 tensor([[2.3027, 2.1648],
        [2.5719, 2.4407],
        [2.3651, 0.2811]]) 
 equals to 
 tensor([[2.3027, 2.1648],
        [2.5719, 2.4407],
        [2.3651, 0.2811]])


In [29]:
# Substract
z = x - y 
z = torch.sub(x, y)
z = y.sub_(x)
print(f"{x - y} \n equals to \n {torch.sub(x, y)} \n equals to \n {y.sub_(x)}")

tensor([[-0.4193, -0.1796],
        [-0.6336, -0.8320],
        [-0.6611, -0.0064]]) 
 equals to 
 tensor([[-0.4193, -0.1796],
        [-0.6336, -0.8320],
        [-0.6611, -0.0064]]) 
 equals to 
 tensor([[0.4193, 0.1796],
        [0.6336, 0.8320],
        [0.6611, 0.0064]])


In [35]:
# Multiply
x = torch.rand(3, 2)
y = torch.rand(3, 1) 
z = torch.mul(x, y)
z

tensor([[0.0676, 0.1596],
        [0.1979, 0.0340],
        [0.1874, 0.0545]])

In [50]:
# Matrix multiplication
x = torch.rand(4, 2).to(device) # 4x2 * 2x6 -> 4x6
y = torch.rand(2, 6).to(device) 
z = torch.matmul(x, y)
z

tensor([[0.7871, 0.8474, 0.4546, 0.8212, 0.0473, 0.4079],
        [1.4799, 0.9771, 0.7988, 1.2030, 0.3401, 0.5850],
        [0.8682, 0.7517, 0.4848, 0.8045, 0.1267, 0.3959],
        [1.5915, 0.9850, 0.8531, 1.2573, 0.3926, 0.6097]], device='cuda:0')

**Slicing Tensors**

In [59]:
x = torch.rand(4, 3)
x

tensor([[0.6427, 0.3589, 0.8240],
        [0.6566, 0.9123, 0.5720],
        [0.8314, 0.0420, 0.4158],
        [0.6590, 0.9863, 0.0971]])

Columnas

In [69]:
# Columna 3
x[:,2]

tensor([0.8240, 0.5720, 0.4158, 0.0971])

Filas

In [68]:
# Fila 2
x[1,:]

tensor([0.6566, 0.9123, 0.5720])

Elemento

In [72]:
# (4, 3) -> 0.0971
x[3, 2]

tensor(0.0971)

**Reshaping tensors**

In [80]:
x = torch.rand(4, 4)
x

tensor([[0.2374, 0.0706, 0.3128, 0.4139],
        [0.0306, 0.0936, 0.3751, 0.5962],
        [0.9432, 0.5884, 0.9008, 0.0653],
        [0.1363, 0.0387, 0.9381, 0.2071]])

In [88]:
# Flatten x
# view(-1, n) infiere el shape de las filas
y = x.view(-1, 8) # 4x4 tensor
y

tensor([[0.2374, 0.0706, 0.3128, 0.4139, 0.0306, 0.0936, 0.3751, 0.5962],
        [0.9432, 0.5884, 0.9008, 0.0653, 0.1363, 0.0387, 0.9381, 0.2071]])

**PyTorch to Numpy**

In [91]:
import numpy as np
a = torch.ones(5)
b = a.numpy()
type(b)

numpy.ndarray

In [92]:
a = np.ones(5)
b = torch.from_numpy(a)
type(b)

torch.Tensor